name       : libkleo
version    : 18.04.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/libkleo-18.04.3.tar.xz : aa5cc5e2d22d21061cff8536959930732320f375c382800e84f490dcf57c3a55
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
