name       : libkleo
version    : 21.12.3
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/libkleo-21.12.3.tar.xz : f47c65970564a0aeeabaa90714023d9f1f9737297900b68fbf5a81d8281201a7
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - libboost-devel
rundeps    :
    - devel :
        - gpgme-qt-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
