name       : libkleo
version    : 18.08.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/libkleo-18.08.0.tar.xz : cc9846880981dfd2e4ada50612b71c115771e382976462b385e97a92ce774c6f
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
