name       : libkleo
version    : 23.04.1
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/libkleo-23.04.1.tar.xz : b51f395cf239020e117382477b5ef1a994f81e2c49978238d26bf685696d8499
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - libboost-devel
rundeps    :
    - devel :
        - gpgme-qt-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
