name       : libkleo
version    : 17.12.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/libkleo-17.12.1.tar.xz : 8c2df1d40029181753051f0d479e2e9f013545be41b8da8fabf4df4e9aa471d5
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM cryptographic library.
description: |
    KDE PIM cryptographic library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
