name       : libkleo
version    : 21.04.2
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/libkleo-21.04.2.tar.xz : 9d797ffbd1e54af2a5f8b787d7f4bfeb7daf451852d61ea2661348e4b3e4f7d5
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - libboost-devel
rundeps    :
    - devel :
        - gpgme-qt-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
