name       : libkleo
version    : 19.12.3
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/libkleo-19.12.3.tar.xz : 1e715442a0c52ca561316abdce9662082f52ad9f3101ea01435a90984989a057
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
