name       : libkleo
version    : 18.08.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/libkleo-18.08.1.tar.xz : 86b9f151818382a7cd0c62bb7084258a0bcfd38cc74cd22b1453c09acb183ae0
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
