name       : libkleo
version    : 20.08.2
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/libkleo-20.08.2.tar.xz : 34537b35e22cef85650ae6f9bf197518bb5a59e9614d6d86ba86f085fddd97c4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : KDE PIM cryptographic library
description: |
    KDE PIM cryptographic library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
